name: build-image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: shreyammaity
          password: ${{ secrets.TOKEN }}
      - name: Build the Portgolio Docker image
        run: |
          docker build . --tag ghcr.io/shreyammaity/shreyammaity.github.io:latest
          docker push ghcr.io/shreyammaity/shreyammaity.github.io:latest
